# Generated by Django 6.0.2 on 2026-03-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=' ', upload_to='post'),
            preserve_default=False,
        ),
    ]
