# Generated by Django 6.0.2 on 2026-03-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
